<a href="https://colab.research.google.com/github/dokeyuka/deep-learning-practice/blob/main/PyTorch_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np



In [3]:
data = [[1,2],[3,4]]
x_data = torch.Tensor(data)

In [5]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [8]:
x_ones  = torch.ones_like(x_data)
print(f"Ones Tensor:\n {x_ones}\n")
x_rand = torch.rand_like(x_data, dtype = torch.float)
print(f"Random Tensor:\n {x_rand}\n")


Ones Tensor:
 tensor([[1., 1.],
        [1., 1.]])

Random Tensor:
 tensor([[0.4707, 0.2121],
        [0.4456, 0.6648]])



In [10]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.0390, 0.0846, 0.3869],
        [0.7105, 0.5761, 0.5060]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [15]:
tensor = torch.rand(3,4)
print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

torch.Size([3, 4])
torch.float32
cpu


In [13]:
if torch.cuda.is_available():
  tenstor = tensor.to('cuda')

In [16]:

print('first row:', tensor[0])#行
print('first column:', tensor[:,0])#列
print('last column:', tensor[...,-1])#最後の列
tensor[:,1] = 0#2列目が全部0
print(tensor)

first row: tensor([0.9081, 0.5599, 0.6281, 0.0515])
first column: tensor([0.9081, 0.9957, 0.0235])
last column: tensor([0.0515, 0.4385, 0.0013])
tensor([[0.9081, 0.0000, 0.6281, 0.0515],
        [0.9957, 0.0000, 0.5745, 0.4385],
        [0.0235, 0.0000, 0.9287, 0.0013]])


In [17]:
t1 = torch.cat([tensor, tensor, tensor], dim = 1)
print(t1)

tensor([[0.9081, 0.0000, 0.6281, 0.0515, 0.9081, 0.0000, 0.6281, 0.0515, 0.9081,
         0.0000, 0.6281, 0.0515],
        [0.9957, 0.0000, 0.5745, 0.4385, 0.9957, 0.0000, 0.5745, 0.4385, 0.9957,
         0.0000, 0.5745, 0.4385],
        [0.0235, 0.0000, 0.9287, 0.0013, 0.0235, 0.0000, 0.9287, 0.0013, 0.0235,
         0.0000, 0.9287, 0.0013]])


In [28]:
tensor = torch.ones(4, 4)
print('First row: ',tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])
tensor[:,1] = 0
print(tensor)

y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [29]:
agg = tensor.sum()
agg_item = agg.item()  
print(agg_item, type(agg_item))

12.0 <class 'float'>
